const comercios = [
  {
    id: 1,
    nombre: "Café Nómade",
    tipo: "Cafetería",
    netlifyName: "cafe-nomade-cfp27-2026-01",
    url: "https://cafe-nomade-cfp27-2026-01.netlify.app",
    estado: "en-construccion",
  },
  {
    id: 2,
    nombre: "Bruma Café",
    tipo: "Cafetería",
    netlifyName: "bruma-cafe-cfp27-2026-02",
    url: "https://bruma-cafe-cfp27-2026-02.netlify.app",
    estado: "en-construccion",
  },
  {
    id: 3,
    nombre: "Patio Central",
    tipo: "Bar",
    netlifyName: "patio-central-cfp27-2026-03",
    url: "https://patio-central-cfp27-2026-03.netlify.app",
    estado: "en-construccion",
  },
  {
    id: 4,
    nombre: "La Esquina Verde",
    tipo: "Restaurante",
    netlifyName: "esquina-verde-cfp27-2026-04",
    url: "https://esquina-verde-cfp27-2026-04.netlify.app",
    estado: "en-construccion",
  },
  {
    id: 5,
    nombre: "Tostado Club",
    tipo: "Cafetería",
    netlifyName: "tostado-club-cfp27-2026-05",
    url: "https://tostado-club-cfp27-2026-05.netlify.app",
    estado: "en-construccion",
  },
  {
    id: 6,
    nombre: "Bodega Urbana",
    tipo: "Bar",
    netlifyName: "bodega-urbana-cfp27-2026-06",
    url: "https://bodega-urbana-cfp27-2026-06.netlify.app",
    estado: "en-construccion",
  },
  {
    id: 7,
    nombre: "Miga y Miel",
    tipo: "Café y pastelería",
    netlifyName: "miga-miel-cfp27-2026-07",
    url: "https://miga-miel-cfp27-2026-07.netlify.app",
    estado: "en-construccion",
  },
  {
    id: 8,
    nombre: "Fuego Lento",
    tipo: "Restaurante",
    netlifyName: "fuego-lento-cfp27-2026-08",
    url: "https://fuego-lento-cfp27-2026-08.netlify.app",
    estado: "en-construccion",
  },
  {
    id: 9,
    nombre: "Estación Café",
    tipo: "Cafetería",
    netlifyName: "estacion-cafe-cfp27-2026-09",
    url: "https://estacion-cafe-cfp27-2026-09.netlify.app",
    estado: "en-construccion",
  },
  {
    id: 10,
    nombre: "Terraza Sur",
    tipo: "Bar y restaurante",
    netlifyName: "terraza-sur-cfp27-2026-10",
    url: "https://terraza-sur-cfp27-2026-10.netlify.app",
    estado: "en-construccion",
  },
];
