/*
===============================================================================
BASE DE DATOS DE PRODUCTOS DE MUESTRA (productos.js)
===============================================================================
Este archivo contiene la lista de productos disponibles en el comercio.
Cada producto es un objeto JavaScript con sus propiedades principales.
===============================================================================
*/

const productos = [
  {
    id: 1,
    nombre: "Latte Nómade",
    descripcion: "Espresso doble, leche texturizada y un toque de miel orgánica.",
    precio: 4800,
    categoria: "Cafés",
    preferencia: "Vegetariano",
    imagen: "latte.png",
    destacado: "Más pedido",
    disponible: true,
  },
  {
    id: 2,
    nombre: "Flat White",
    descripcion: "Doble ristretto con leche sedosa y sabor intenso a café.",
    precio: 4500,
    categoria: "Cafés",
    preferencia: "Vegetariano",
    imagen: "latte.png",
    destacado: "",
    disponible: true,
  },
  {
    id: 3,
    nombre: "Cold Brew Cítrico",
    descripcion: "Café infusionado en frío durante 18hs, rodaja de naranja y tónica.",
    precio: 5200,
    categoria: "Bebidas frías",
    preferencia: "Vegano",
    imagen: "latte.png",
    destacado: "Nuevo",
    disponible: true,
  },
  {
    id: 4,
    nombre: "Limonada Menta y Jengibre",
    descripcion: "Limón fresco, menta de la huerta, almíbar casero y jengibre.",
    precio: 4300,
    categoria: "Bebidas frías",
    preferencia: "Vegano",
    imagen: "latte.png",
    destacado: "",
    disponible: true,
  },
  {
    id: 5,
    nombre: "Tostón Palta y Huevo",
    descripcion: "Pan de masa madre, palta pisada, huevo poché y semillas de sésamo.",
    precio: 8900,
    categoria: "Desayunos",
    preferencia: "Sin lactosa",
    imagen: "toston.png",
    destacado: "Más pedido",
    disponible: true,
  },
  {
    id: 6,
    nombre: "Yogur con Granola y Miel",
    descripcion: "Yogur natural artesanal, granola horneada en casa y frutas frescas.",
    precio: 6100,
    categoria: "Desayunos",
    preferencia: "Vegetariano",
    imagen: "toston.png",
    destacado: "",
    disponible: true,
  },
  {
    id: 7,
    nombre: "Sándwich de Focaccia",
    descripcion: "Focaccia casera, vegetales asados, queso halloumi y pesto de albahaca.",
    precio: 9800,
    categoria: "Platos",
    preferencia: "Vegetariano",
    imagen: "toston.png",
    destacado: "",
    disponible: true,
  },
  {
    id: 8,
    nombre: "Bowl del Mercado",
    descripcion: "Arroz yamaní, calabaza asada, verdes de estación y aderezo tahini.",
    precio: 9400,
    categoria: "Platos",
    preferencia: "Vegano",
    imagen: "toston.png",
    destacado: "",
    disponible: false, // Ejemplo de producto agotado
  },
  {
    id: 9,
    nombre: "Torta Húmeda de Chocolate",
    descripcion: "Chocolate semiamargo al 70%, ganache suave y escamas de sal marina.",
    precio: 6200,
    categoria: "Dulces",
    preferencia: "Vegetariano",
    imagen: "torta.png",
    destacado: "Nuevo",
    disponible: true,
  },
  {
    id: 10,
    nombre: "Roll de Canela",
    descripcion: "Masa de brioche hojaldrada, canela ceylán y glaseado de naranja.",
    precio: 4900,
    categoria: "Dulces",
    preferencia: "Vegetariano",
    imagen: "torta.png",
    destacado: "",
    disponible: true,
  },
  {
    id: 11,
    nombre: "Cookie Choco-Nuez",
    descripcion: "Galleta horneada en el día con trozos de chocolate amargo y nueces.",
    precio: 3500,
    categoria: "Dulces",
    preferencia: "Vegetariano",
    imagen: "torta.png",
    destacado: "",
    disponible: true,
  },
  {
    id: 12,
    nombre: "Affogato de Vainilla",
    descripcion: "Bocha de helado de vainilla artesanal bañada con espresso caliente.",
    precio: 5800,
    categoria: "Cafés",
    preferencia: "Vegetariano",
    imagen: "latte.png",
    destacado: "",
    disponible: true,
  }
];
