const productos = [
  {
    id: 1,
    nombre: "Latte Nómade",
    descripcion: "Espresso doble, leche texturizada y un toque de miel.",
    precio: 4800,
    categoria: "Cafés",
    preferencia: "Vegetariano",
    imagen: "latte.jpg",
    destacado: "Más pedido",
    disponible: true,
  },
  {
    id: 2,
    nombre: "Flat white",
    descripcion: "Doble ristretto con leche sedosa y sabor intenso.",
    precio: 4500,
    categoria: "Cafés",
    preferencia: "Vegetariano",
    imagen: "latte.jpg",
    destacado: "",
    disponible: true,
  },
  {
    id: 3,
    nombre: "Cold brew cítrico",
    descripcion: "Café infusionado en frío, naranja y agua tónica.",
    precio: 5200,
    categoria: "Bebidas frías",
    preferencia: "Vegano",
    imagen: "latte.jpg",
    destacado: "Nuevo",
    disponible: true,
  },
  {
    id: 4,
    nombre: "Limonada de estación",
    descripcion: "Limón, almíbar casero, menta y fruta de estación.",
    precio: 4300,
    categoria: "Bebidas frías",
    preferencia: "Vegano",
    imagen: "latte.jpg",
    destacado: "",
    disponible: true,
  },
  {
    id: 5,
    nombre: "Tostón del patio",
    descripcion: "Pan de masa madre, palta, huevo poché y hojas frescas.",
    precio: 8900,
    categoria: "Desayunos",
    preferencia: "Sin lactosa",
    imagen: "toston.jpg",
    destacado: "Más pedido",
    disponible: true,
  },
  {
    id: 6,
    nombre: "Yogur con granola",
    descripcion: "Yogur natural, granola de la casa, miel y frutas.",
    precio: 6100,
    categoria: "Desayunos",
    preferencia: "Vegetariano",
    imagen: "toston.jpg",
    destacado: "",
    disponible: true,
  },
  {
    id: 7,
    nombre: "Sándwich de focaccia",
    descripcion: "Focaccia, vegetales asados, queso y pesto suave.",
    precio: 9800,
    categoria: "Platos",
    preferencia: "Vegetariano",
    imagen: "toston.jpg",
    destacado: "",
    disponible: true,
  },
  {
    id: 8,
    nombre: "Bowl del mercado",
    descripcion: "Arroz yamaní, calabaza, verdes, semillas y tahini.",
    precio: 9400,
    categoria: "Platos",
    preferencia: "Vegano",
    imagen: "toston.jpg",
    destacado: "",
    disponible: false,
  },
  {
    id: 9,
    nombre: "Torta húmeda",
    descripcion: "Chocolate semiamargo, ganache y sal marina.",
    precio: 6200,
    categoria: "Dulces",
    preferencia: "Vegetariano",
    imagen: "torta.jpg",
    destacado: "Nuevo",
    disponible: true,
  },
  {
    id: 10,
    nombre: "Roll de canela",
    descripcion: "Masa brioche, canela, nueces y glaseado de naranja.",
    precio: 4900,
    categoria: "Dulces",
    preferencia: "Vegetariano",
    imagen: "torta.jpg",
    destacado: "",
    disponible: true,
  },
  {
    id: 11,
    nombre: "Cookie de chocolate",
    descripcion: "Chocolate amargo, nueces pecán y centro suave.",
    precio: 3500,
    categoria: "Dulces",
    preferencia: "Vegetariano",
    imagen: "torta.jpg",
    destacado: "",
    disponible: true,
  },
  {
    id: 12,
    nombre: "Affogato",
    descripcion: "Helado de vainilla artesanal y espresso recién hecho.",
    precio: 5800,
    categoria: "Cafés",
    preferencia: "Vegetariano",
    imagen: "latte.jpg",
    destacado: "",
    disponible: true,
  },
];
